version: 2.1

executors:
  go:
    parameters:
      go-version:
        type: string
    docker:
      - image: circleci/golang:<<parameters.go-version>>
        environment:
          GO111MODULE: "on"

commands:
  restore_module:
    steps:
      - restore_cache:
          name: Restore go module cahce
          keys:
            - mod-{{ checksum "go.sum" }}

  save_module:
    steps:
      - save_cache:
          name: Save go module cache
          key: mod-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod

  vendoring:
    steps:
      - run:
          name: Vendoring
          command: go mod download

  test:
    steps:
      - run:
          name: go test
          command: go test -v ./...

  install_golangci-lint:
    steps:
      - run:
          name: install golangci-lint
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.15.0

  run_golangci-lint:
    steps:
      - run:
          name: run_golangci-lint
          command: ./bin/golangci-lint run --disable-all --enable=goimports --enable=golint --enable=errcheck

jobs:
  build:
    executor:
      name: go
      go-version: "1.16.0"
    steps:
      - checkout
      - restore_module
      - vendoring
      - save_module
      - test
      - install_golangci-lint
      - run_golangci-lint
