version: 2.1

executors:
  go:
    parameters:
      go-version:
        type: string
    docker:
      - image: circleci/golang:<<parameters.go-version>>
        environment:
          GO111MODULE: "on"

commands:
  restore_module:
    steps:
      - restore_cache:
          name: restore go module cahce
          keys:
            - mod-{{ checksum "go.sum" }}

  save_module:
    steps:
      - save_cache:
          name: save go module cache
          key: mod-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod

  vendoring:
    steps:
      - run:
          name: vendoring
          command: go mod download

  install-golangci-lint:
    steps:
      - restore_cache:
          keys:
            - v1-golangci-lint-1.38.0
      - run: bash <(curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh) -b ~/.bin v1.38.0
      - save_cache:
          key: v1-golangci-lint-1.38.0
          paths:
            - ~/.bin

  golangci-lint:
    steps:
      - run:
          name: run golangci-lint 
          command: PATH=$HOME/.bin:$PATH GOGC=100 golangci-lint run --disable-all --enable=goimports --enable=golint --enable=errcheck
  
  test:
    steps:
      - run:
          name: go test
          command: go test -v ./...

jobs:
  build-lint-test:
    executor:
      name: go
      go-version: "1.16.0"
    steps:
      - checkout
      - restore_module
      - vendoring
      - save_module
      - install-golangci-lint
      - golangci-lint
      - test
