version: 2.1

executors:
  go:
    parameters:
      go-version:
        type: string
    docker:
      - image: circleci/golang:<<parameters.go-version>>
        environment:
          GO111MODULE: "on"

commands:
  restore_module:
    steps:
      - restore_cache:
          name: restore go module cahce
          keys:
            - mod-{{ checksum "go.sum" }}

  save_module:
    steps:
      - save_cache:
          name: save go module cache
          key: mod-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod

  vendoring:
    steps:
      - run:
          name: vendoring
          command: go mod download

  test:
    steps:
      - run:
          name: go test
          command: go test -v ./...

jobs:
  build:
    executor:
      name: go
      go-version: "1.16.0"

    steps:
      - checkout
      - restore_module
      - vendoring
      - save_module
      - test
      - run: go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
      - run: golangci-lint run --disable-all --enable=goimports --enable=golint
